language: node_js
services:
  - docker
before_script:
  - npm run test -- --silent --noStackTrace
script:
  - docker build . -t cert-verifier-js
  - docker run -p 9000:4000 -d cert-verifier-js
  - curl -i localhost:9000
