language: node_js
dist: focal
branches:
  only:
    - main
services:
  - docker
before_script:
  - npm run test -- --silent --noStackTrace
  - npm run semantic-release
script:
  - npm run build
  - npm run start
  - npm run test:docker
  - cd node_modules/vc-api-verifier-test-suite
  - npm install
  - npm run test
  - cd ../..
after_script:
  - sh scripts/update-version-static-file.sh
