FROM node:22-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm ci
RUN rm -rf node_modules/@blockcerts/cert-verifier-js

# Bundle app source
COPY . .

# transpile typescript
RUN npx tsc -p tsconfig.build.json

EXPOSE 4000
CMD [ "node", "src/server.js" ]
